routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// login logout 
Route::get('/login', 'Admin\LoginController@getLogin')->name('admin.login');
Route::post('/postlogin', 'Admin\LoginController@postLogin')->name('admin.post.login');

// backend
Route::group(['prefix' => 'admin','middleware' => 'auth'], function() {

    Route::get('/dashboard', function () {
        return view('backend.index');
    });

    Auth::routes();

    //category
    Route::resource('category','Admin\CategoryController');
    Route::resource('kind','Admin\KindController');
    Route::resource('details','Admin\DetailsController');

    Route::get('/kindnew/{id}','Admin\AjaxController@getKind');
    



// logout admin
Route::get('/getlogout', 'Admin\LoginController@getLogout')->name('admin.logout');

});

// frontend
Route::get('/index', 'Frontend\PageController@getIndex')->name('home');

app/Models/Details.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Details extends Model
{
    //
    protected $table = 'new_details';

    protected $fillable = [
        'new_id', 'new_title','new_slug','new_describe','new_content','new_image','new_hot','new_view','new_kind',
    ];
}

app/Http/Controllers/Admin/DetailsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Kind;
use App\Models\Details;

class DetailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $cat = Category::all();
        $kind = Kind::all();

        return view('backend.details.add',compact('cat','kind'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $news = new Details;

        $news->new_title = $request->title;
        $news->new_slug = changeTitle($request->slug);
        $news->new_describe = $request->describe;
        $news->new_content = $request->editor1;
        $news->new_hot = $request->newhot;
        $news->new_kind = $request->kind_id;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $name = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/uploadfile/news_img');
            $image->move($destinationPath, $name);
            $news->new_image = $name;
    
        }

        $news->save();

        return back()->with('success','bạn đã thêm thành công');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/details/add.blade.php
@extends('backend.layout.master')
@section('content')



<section class="content">
        <div class="row">
                @if (session('success'))
                    <div class="alert alert-success">
                        <strong>{{ session('success') }}</strong>
                    </div>
                @endif
            <div class="col-md-12">
            <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Thêm tin tức</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="post" action="{{ route('details.store')}}" enctype="multipart/form-data">
            {{ csrf_field() }}
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Tiêu đề tin tức</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên danh mục" name="title">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Tên không dấu</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên không dấu" name="slug">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Mô tả ngắn</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên không dấu" name="describe">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Nội dung bài viết</label>
                    <textarea name="editor1"></textarea>
                </div>
                

                <div class="form-group">
                  <label for="exampleInputFile">Ảnh đại diện bài viết</label>
                  <input type="file" id="exampleInputFile" name="image">
                  <p class="help-block">Nhập ảnh đại diện bài viết</p>
                </div>

                <div class="checkbox">
                  <label>
                    <input type="radio" name="newhot" value="0" checked> Tin thường
                  </label>
                  <label style="margin-left: 10px;">
                    <input type="radio" name="newhot" value="1"> Tin nổi bật
                  </label>
                </div>

                <div class="form-group">
                    <label for="sel1">Thể loại</label>
                    <select class="form-control" id="cat" onchange="getChild(this)">
                    @foreach( $cat as $ca)
                        <option value="{{ $ca->cat_id }}">{{ $ca->cat_name }}</option>
                    @endforeach
                    </select>
                    
                </div>

                <div class="form-group">
                    <label for="sel1">Loại tin</label>
                    <select class="form-control" id="kind" name="kind_id">
                    @foreach( $kind as $kin)
                        <option value="{{$kin->kind_id}}">{{ $kin->kind_name }}</option>
                    @endforeach
                    </select>
                </div>


              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Lưu lại
            </form>
          </div>
            </div>
        </div>
        

</section>


@endsection

@section('script')
    <script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
    <script src="https://cdn.ckeditor.com/[version.number]/[distribution]/ckeditor.js"></script>
    <script>
            CKEDITOR.replace( 'editor1' );
    </script>
    <script>
            $(document).ready(function(){
                $('.alert-success').delay(4000).slideUp();
            });
    </script>

    <script>
        function getChild(opj){
          var id_cat = $(opj).val();
          $.get("/admin/kindnew/"+id_cat,function(data){
                    $("#kind").html(data);
                });
        }
    </script>
@endsection