routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// login logout 
Route::get('/login', 'Admin\LoginController@getLogin')->name('admin.login');
Route::post('/postlogin', 'Admin\LoginController@postLogin')->name('admin.post.login');

// backend
Route::group(['prefix' => 'admin','middleware' => 'auth'], function() {

    Route::get('/dashboard', function () {
        return view('backend.index');
    });

    Auth::routes();

    //category
    Route::resource('category','Admin\CategoryController');
    Route::resource('kind','Admin\KindController');
    Route::resource('details','Admin\DetailsController');

    Route::get('/kindnew/{id}','Admin\AjaxController@getKind');
    



// logout admin
Route::get('/getlogout', 'Admin\LoginController@getLogout')->name('admin.logout');

});

// frontend
Route::get('/index', 'Frontend\PageController@getIndex')->name('home');

app/Models/Kind.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Kind extends Model
{
    //
    protected $table = 'new_kind';

    protected $fillable = [
        'kin_id', 'kind_cat','kind_name','kind_slug',
    ];
}

app/Http/Controllers/Admin/KindController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Kind;
use App\Models\Category;

class KindController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $cat = Category::all();
        

        return view('backend.kind.add',compact('cat'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $kind = new Kind;
        $kind->Kind_name = $request->name;
        $kind->Kind_slug = changeTitle($request->slug);
        $kind->Kind_cat = $request->cat_id;

        $kind->save();

        return back()->with('success','bạn đã thêm thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/kind/add.blade.php
@extends('backend.layout.master')
@section('content')

<section class="content">
        <div class="row">
                @if (session('success'))
                    <div class="alert alert-success">
                        <strong>{{ session('success') }}</strong>
                    </div>
                @endif
            <div class="col-md-6">
            <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Thêm loại tin</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="post" action="{{ route('kind.store')}}">
            {{ csrf_field() }}
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Tên loại tin</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên danh mục" name="name">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Tên không dấu</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên không dấu" name="slug">
                </div>
                <div class="form-group">
                    <label>Loại danh mục</label>
                    <select multiple="" class="form-control" name="cat_id">
                    @foreach($cat as $ca)
                    <option value="{{ $ca->cat_id }}">{{ $ca->cat_name }}</option>
                    @endforeach
                    </select>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Lưu lại
            </form>
          </div>
            </div>
        </div>
</section>


@endsection

@section('script')
    <script>
            $(document).ready(function(){
                $('.alert-success').delay(4000).slideUp();
            });
    </script>
@endsection