routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// login logout 
Route::get('/login', 'Admin\LoginController@getLogin')->name('admin.login');
Route::post('/postlogin', 'Admin\LoginController@postLogin')->name('admin.post.login');

// backend
Route::group(['prefix' => 'admin','middleware' => 'auth'], function() {

    Route::get('/dashboard', function () {
        return view('backend.index');
    });

    Auth::routes();

    //category
    Route::resource('category','Admin\CategoryController');
    Route::resource('kind','Admin\KindController');
    Route::resource('details','Admin\DetailsController');

    Route::get('/kindnew/{id}','Admin\AjaxController@getKind');
    



// logout admin
Route::get('/getlogout', 'Admin\LoginController@getLogout')->name('admin.logout');

});

// frontend
Route::get('/index', 'Frontend\PageController@getIndex')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $table = 'category';
    protected $primaryKey = 'cat_id';

    protected $fillable = [
        'cat_id', 'cat_name','cat_slug',
    ];
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cat = Category::all();
        // dd($cat);
        return view('backend.category.list',compact('cat'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('backend.category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $cat = new Category;
        $cat->cat_name = $request->name;
        $cat->cat_slug = changeTitle($request->slug);

        
        $cat->save();

        return back()->with('success','bạn đã thêm thành công');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $cat = Category::findOrFail($id);

        return view('backend.category.edit',compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $cat = Category::findOrFail($id);
        $cat->cat_name = $request->name;
        $cat->cat_slug = changeTitle($request->slug);

        
        $cat->save();

        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $cat = Category::findOrFail($id);
        $cat->delete();

        return redirect()->back();
    }
}

resources/views/backend/category/add.blade.php
@extends('backend.layout.master')
@section('content')

<section class="content">
        <div class="row">
                @if (session('success'))
                    <div class="alert alert-success">
                        <strong>{{ session('success') }}</strong>
                    </div>
                @endif
            <div class="col-md-6">
            <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Thêm danh mục</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="post" action="{{ route('category.store')}}">
            {{ csrf_field() }}
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Tên danh mục</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên danh mục" name="name">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Tên không dấu</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên không dấu" name="slug">
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Lưu lại
            </form>
          </div>
            </div>
        </div>
</section>


@endsection

@section('script')
    
    <script>
            $(document).ready(function(){
                $('.alert-success').delay(4000).slideUp();
            });
    </script>

    
@endsection

resources/views/backend/category/edit.blade.php
@extends('backend.layout.master')
@section('content')

<section class="content">
        <div class="row">
                @if (session('success'))
                    <div class="alert alert-success">
                        <strong>{{ session('success') }}</strong>
                    </div>
                @endif
            <div class="col-md-6">
            <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Thêm danh mục</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="post" action="{{ route('category.update', ['id' => $cat->cat_id]) }}">
            {{ csrf_field() }}
            @method('PUT')
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Tên danh mục</label>
                <input type="text" class="form-control" id="" placeholder="nhập tên danh mục" name="name" value="{{$cat->cat_name}}">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Tên không dấu</label>
                  <input type="text" class="form-control" id="" placeholder="nhập tên không dấu" name="slug" value="{{$cat->cat_slug}}">
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Lưu lại
            </form>
          </div>
            </div>
        </div>
</section>


@endsection

@section('script')
    
    <script>
            $(document).ready(function(){
                $('.alert-success').delay(4000).slideUp();
            });
    </script>

    
@endsection

resources/views/backend/category/list.blade.php
@extends('backend.layout.master')
@section('content')

<section class="content">
        <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Danh sách thể loại</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Tên thể loại</th>
                  <th>Ngày tạo</th>
                  <th>Tên không dấu</th>
                  <th>Hành động</th>
                </tr>
                @foreach($cat as $ca)
                <tr>
                  <td>{{$ca->cat_id}}</td>
                  <td>{{$ca->cat_name}}</td>
                  <td>{{$ca->created_at}}</td>
                  <td>{{$ca->cat_slug}}</td>
                <td><button type="button" class="btn btn-block btn-success btn-sm"><a href="{{ route('category.edit', ['id' => $ca->cat_id]) }}" style="color: #fff;">Sửa</a></button>
                  <button type="button" class="btn btn-block btn-danger btn-sm"><a href="{{ route('category.destroy', ['id' => $ca->cat_id]) }}" style="color: #fff;">Xóa</a></button></td>
                </tr>
                @endforeach
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        </div>
</section>

@endsection



@section('script')
    <script>
            $(document).ready(function(){
                $('.alert-success').delay(4000).slideUp();
            });
    </script>
@endsection